TycheSoftwares/woocommerce-delivery-notes

woocommerce-delivery-notes/readme.txt, woocommerce-delivery-notes/woocommerce-delivery-notes.php
= 4.3.2 (05.09.2017) =
* In this version deprecated functions and classes have been removed.
Because of that attributes were missing and attribute slug was getting
printed on Invoice page. This has been fixed.
* Fix - There was no line break before SKU element for variable products
on Invoice page. This has been fixed.
* Fix - The deprecated function WC_Order::get_order_currency has been
removed and replaced with get_currency().
=> Version 4.3.2

woocommerce-delivery-notes/readme.txt
Changelog for WooCommerce Print Invoice & Delivery Note v4.4
= 4.4 (29.12.2017) =
* This version has 1 bug fix.
* Fix - Earlier with WooCommerce Local Pickup Plus v2.x.x, pickup locations were not displayed on the invoices, delivery notes & receipts. Now, the plugin is compatible with it and it will display the pickup locations. 
* Code Enhancement - Now, the plugin has the uninstall file for deleting the plugin options.
=> Version 4.4

woocommerce-delivery-notes/css/admin.css
As #37 was indicating, there is a bug where the order table listing icons are not being displayed in WC 3.3.1. This was a result of a CSS class name change. This PR is a fix for this. I have fixed it for WC 3.3.1+ while keeping it backwards compatible to older versions of WC. I hope this helps.
=> Fixed order table action icons for WC 3.3.1

woocommerce-delivery-notes/includes/class-wcdn-settings.php
Reset tracking button was missing from the settings page it has been added.
=> Added missing reset tracking button on settings page

woocommerce-delivery-notes/includes/component/pro-notices-in-lite/ts-pro-notices.php
The notices displaying variable for booking notice was wrong so it was displyed immediatly
=> Booking notices displayed immediately

woocommerce-delivery-notes/includes/class-wcdn-theme.php
I wanted to change the template type according to any order status.
So I added the following filter hook.
- `wcdn_theme_print_button_template_type_arbitrary`
For example, use as follows.
```
add_filter( 'wcdn_theme_print_button_template_type_arbitrary', function( $type, $order ) {
if ( 'completed' === $order->get_status() ) {
$type = 'receipt';
} else if ( 'on-hold' === $order->get_status() ) {
$type = 'invoice';
} else {
$type = 'order';
}
return $type;
}, 10, 2 );
```
=> Add filter to change template type arbitrarily

woocommerce-delivery-notes/includes/class-wcdn-theme.php
I wanted to change the name of the print button.
So I added the following filter hooks.
- `wcdn_print_button_name_on_my_account_page`
- `wcdn_print_button_name_order_page`
For example, use as follows.
```
add_filter( 'wcdn_print_button_name_on_my_account_page', function( $name, $order ) {
if ( 'completed' === $order->get_status() ) {
$name = 'Print Invoice';
} else {
$name = 'Print Order';
}
return $name;
}, 10, 2);
```
=> Add buttom name filters

woocommerce-delivery-notes/includes/wcdn-template-functions.php
Removed esc_html_e & replaced with esc_html(). It was wrongly used on a variable that's only a file name. Due to this, the CSS file style.css was not loading, hence the template format was not coming proper.
Fix #93
=> Removed esc_html_e & replaced with esc_html

woocommerce-delivery-notes/includes/class-woocommerce-delivery-notes.php, woocommerce-delivery-notes/readme.txt, woocommerce-delivery-notes/woocommerce-delivery-notes.php
Changelog for v4.4.9
1. Made the plugin code compliant with WPCS coding standards
2. Added 3 new filters:
- wcdn_theme_print_button_template_type_arbitrary - this filter hook allows to change template type based on order status
- wcdn_print_button_name_on_my_account_page, wcdn_print_button_name_order_page - this filter hook allows to change the label of the Print button
3. When plugin is uninstalled, data cleanup wasn't happening. This has been fixed.
=> Version 4.4.9

woocommerce-delivery-notes/includes/class-woocommerce-delivery-notes.php, woocommerce-delivery-notes/readme.txt, woocommerce-delivery-notes/woocommerce-delivery-notes.php
= 4.5.1 (21.08.2019) =
* Fixed the issue of Print buttons not showing up on Order details page after the 4.4.9 update.
=> Version 4.5.1

woocommerce-delivery-notes/includes/class-woocommerce-delivery-notes.php
The dirname() was causing the issue with PHP versions lower then 7.0 due to it's optional 2nd parameter. Fix #105
=> Fix for print not working for PHP below 7.0

woocommerce-delivery-notes/templates/print-order/print-content.php
All hooks placed inside order items loop require $item (WC_Order_Item) param for correct accessing data.
- Add $item (WC_Order_Item) param to 'wcdn_order_item_before' action;
- Add $item (WC_Order_Item) param to 'wcdn_order_item_fields' filter;
- Add 'wcdn_order_item_after' action after the product name column content;
=> Allow 3rd party code to add order item data on the print-content.php template

woocommerce-delivery-notes/templates/print-order/print-content.php
Function using was deprecated from WC4.4.0 hence changed the function which will not return errors in debug log.
=> Function using was deprecated from WC4.4.0 hence changed the function which will not return errors in debug log

woocommerce-delivery-notes/templates/print-order/print-content.php
One can hide the child products in Composite Products through this filter :-'wcdn_order_item_product'
=> Hide the child products in Composite Products through filter

woocommerce-delivery-notes/templates/print-order/print-content.php
The key is useful for functions that require $item_id. For instance, $order->get_qty_refunded_for_item($item_id) to get refunded qty for an item.
=> Make order item object key available in foreach loop

woocommerce-delivery-notes/templates/print-order/print-content.php
When printing receipts, the number of downloaded files is displayed as "%s files".
=> The number of downloaded files is not displayed correctly when printing receipts.

includes/class-woocommerce-delivery-notes.php, readme.txt, woocommerce-delivery-notes.php
This was added in 4.7.0, which is now reverted back.
=> Removed the labels for shipping and billing address.

includes/class-wcdn-writepanel.php
"handle_bulk_actions-edit-shop_order" is a filter, which should return a value, not just null, because other plugins might customized it already. This causes issues, like showing a white screen instead of handling the bulk action.
=> Fix bulk action handling incompatibility

woocommerce-delivery-notes.php
Fix #300. This issue occurred due to the renamed folder. However, we added this line as it is included in all our other plugins. If WooCommerce has this feature, it should be added.
=> Fixed HPOS Compatibility

templates/print-order/simple/receipt/print-content.php, templates/print-order/simple/style.css
Fix #316. When the simple template is active, a payment received stamp is now added to the admin side receipt print link.
=> Fixed Payment Received stamp is not working in receipt templates setting

assets/js/admin.js
Fix #322. I have added a check to block all fields when the default type is selected or clicked.
=> Fixed Disable all the field when the default template is selected.

assets/css/admin.css, includes/admin/views/Preview_template/deliverynote-preview-template.php, includes/admin/views/Preview_template/invoice-preview-template.php, includes/admin/views/Preview_template/receipt-preview-template.php, includes/admin/views/wcdn-document.php, includes/admin/views/wcdn-general.php, includes/wcdn-template-functions.php, templates/print-order/print-content.php
1. remove logo size for  the default template.
2. Set payment date in live preview. when the payment date is not there in last order it is showing order date.
3. Fix space issue for invoice and receipt. [https://prnt.sc/scn5trkGLsgT](https://prnt.sc/scn5trkGLsgT)
4. in simple template live preview the invoice number is not showing when the last order has no invoice number . so i have added Next number in to that. with the condition. if invoice number is not present in last order it wil show the next number of numbering setting.
=> remove logo size for default template

includes/wcdn-template-functions.php
remove store time the year format will not properly showing in order date. [https://prnt.sc/hovWqe9zrGw_](https://prnt.sc/hovWqe9zrGw_)
$wdn_order_order_date is already a timestamp, there's no need to use strtotime on it so i have remove it.
=> remove store time

templates/pdf/default/deliverynote/template.php, templates/pdf/default/invoice/template.php, templates/pdf/default/receipt/template.php, templates/pdf/simple/deliverynote/template.php, templates/pdf/simple/invoice/template.php, templates/pdf/simple/receipt/template.php
Fix #370 added wcdn_head hook in the PDF default & simple both templates. This hook will not added to the live preview because we are not going to directly apply a style tag in the live preview due to the vue.js implementation. It will show an error if we add a style tag to this.
=> Fix #370 added wcdn_head hook in PDF template.

templates/pdf/default/style.css
Set font-size: 7pt; to the default PDF template. so the template will look properly and not create multiple pages. with 2,4 products. 
output after changes- [https://prnt.sc/JnNJrJibOCGi](url)
Ticket- [https://wordpress.org/support/topic/pdf-invoice-is-massive/](url)
=> Fix PDF Font size for default template.

includes/class-woocommerce-delivery-notes.php
Fix #385 prints buttons are not showing on order edit page. the issue is for fresh instalments, the fields database is not there in DB table so it is not appearing.
=> Fix #385 prints buttons are not showing

assets/js/admin.js
This pull request fixes an error that occurred when loading the [admin.js](https://github.com/TycheSoftwares/woocommerce-delivery-notes/blob/461fcef3bf3c3ff267a98c402cc0d2a8226ada30/includes/class-wcdn-writepanel.php#L67) script on WooCommerce order edit and listing pages. The error happened because the wp_localize_script for the woocommerce-delivery-notes-admin script was not triggered on these pages, resulting in the absence of the  #admin_object.
Also, a conditional check was added to the tooltip function.
Error reported in: [https://wordpress.org/support/topic/order-printing-tab-wont-display-any-buttons-on-order-page-in-backend/](https://wordpress.org/support/topic/order-printing-tab-wont-display-any-buttons-on-order-page-in-backend/)
Enhancements:
* Added a check to ensure …
=> Fix admin.js loading error on order edit and listing pages

includes/class-wcdn-print.php
When visiting a different customer's invoice, the following messages are displayed and they are not very easy to change.
```
You need to be logged into your account to access the Invoice. Please login first.
Proceed to Login
```
So, I would like to make it better to customize these messages through the i18n feature of WordPress.
Thank you.
=> To improve customizability of the need login message

includes/admin/views/Preview_template/default-preview-template.php, templates/print-order/print-content.php
Fix #456 YITH WooCommerce Product Add-Ons meta key is showing in addon.
Added handling for YITH add-ons to display labels/values properly in print templates.
Implemented cleanup to remove raw ywapo-* meta fields and avoid duplicate outputs.
=> Fix #456 YITH WooCommerce Product Add-Ons meta key is showing in addon.
