README.md

Chnged the announcement of the readme file

read me file changes

---

woocommerce-delivery-notes/readme.txt
woocommerce-delivery-notes/woocommerce-delivery-notes.php

* This version has 1 bug fix.
* Fix - The attributes of the variable product were not displayed with the variable name in the Print screen. This has been fixed.

Version 4.3.1

---

woocommerce-delivery-notes/templates/print-order/print-content.php

Unwanted attributes are getting printed on invoice.
while testing test on woo-order, my account , checkout pages.

unwanted attributes

---

woocommerce-delivery-notes/templates/print-order/print-content.php

Fix the notice of deprecated function displayed on the invoices of downloadable products.

Fixes #22-Fix the notice on downloadable products

---

woocommerce-delivery-notes/readme.md
woocommerce-delivery-notes/readme.txt
woocommerce-delivery-notes/templates/print-order/print-content.php
woocommerce-delivery-notes/woocommerce-delivery-notes.php

* .po and .mo files for Japanese and Norwegian language is added in the plugin. The plugin strings can now be translated to this languages using these files.

Version 4.3.4

---

woocommerce-delivery-notes/includes/wcdn-template-functions.php

Fix for invoice date not appearing translated

---

woocommerce-delivery-notes/readme.txt
woocommerce-delivery-notes/woocommerce-delivery-notes.php

Remove halloween discount & update version number

Remove halloween discount & update version number

---

woocommerce-delivery-notes/includes/class-wcdn-settings.php

Remove Pro version link

---

woocommerce-delivery-notes/includes/class-wcdn-print.php

This fix ensures that if the LPP v2.x.x is enabled then it will add the local pickup address in the print invoice.

LPP Compatibility v2.x.x

---

woocommerce-delivery-notes/templates/print-order/print-content.php

Removed unwanted code

---

woocommerce-delivery-notes/includes/class-wcdn-print.php
woocommerce-delivery-notes/readme.txt
woocommerce-delivery-notes/woocommerce-delivery-notes.php

= 4.4.1 (29.12.2017) =
* This version has 1 bug fix.
* Fix - PHP short tag was inadvertently added in the plugin in v4.4, which was causing an error. This has been fixed.

Version 4.4.1

---

woocommerce-delivery-notes/includes/class-wcdn-print.php
woocommerce-delivery-notes/includes/class-wcdn-settings.php
woocommerce-delivery-notes/includes/class-wcdn-theme.php
woocommerce-delivery-notes/includes/class-wcdn-writepanel.php
woocommerce-delivery-notes/woocommerce-delivery-notes.php

Add comments to missing classes & functions

add missing comments

---

woocommerce-delivery-notes/includes/component/tracking-data/class-ts-tracker.php
woocommerce-delivery-notes/includes/component/tracking-data/ts-tracking.php

We have added prefix for option ts_tracker_last_send. So it will be plugin specific.

Added Prefix for the option ts_tracker_last_send

---

woocommerce-delivery-notes/includes/component/pro-notices-in-lite/ts-pro-notices.php
woocommerce-delivery-notes/uninstall.php

We have deleted boilerplate options while we uninstall the plugin.

Delet boilerplate options while uninstalling of plugin

---

woocommerce-delivery-notes/includes/wcdn-all-component.php

Add 6th, 7th, 8th & 9th notice as that of AC Pro plugin.
Add 10th, 11th, 12th & 13th notice as that of other 4 plugins.

Change notices

---

woocommerce-delivery-notes/includes/component/pro-notices-in-lite/ts-pro-notices.php
woocommerce-delivery-notes/includes/wcdn-all-component.php

Added new notices for the pro plugins
changed the tracking usage link.

Added New pro notices in the plugin

---

woocommerce-delivery-notes/includes/component/welcome-page/templates/welcome/welcome-page.php

Chnaged the premium plugin link in welcome page.

Changed the premium plugin link

---

woocommerce-delivery-notes/includes/component/tracking-data/ts-tracking.php

Tracking usage link opened in a new tab

Tracking Usage link opened in new tab

---

woocommerce-delivery-notes/includes/component/pro-notices-in-lite/ts-pro-notices.php

We have removed the unwanted code from conditions which were used to display the pro notices.

Code Optimised for displaying Pro notices

---

woocommerce-delivery-notes/includes/component/pro-notices-in-lite/ts-pro-notices.php
woocommerce-delivery-notes/readme.txt
woocommerce-delivery-notes/woocommerce-delivery-notes.php

Changed version number and pro notice time.

Version 4.4.3

---

woocommerce-delivery-notes/readme.txt

Chnages for Ream me file for v4.4.3

Changes in Read me file for v4.4.3

---

woocommerce-delivery-notes/includes/wcdn-all-component.php
woocommerce-delivery-notes/woocommerce-delivery-notes.php

Now welcome pages will be displayed only for the admin users.

Welcome page will be displayed for admin users only

---

woocommerce-delivery-notes/readme.txt
woocommerce-delivery-notes/woocommerce-delivery-notes.php

Version 4.4.5

---

woocommerce-delivery-notes/readme.txt
woocommerce-delivery-notes/woocommerce-delivery-notes.php

= 4.4.6 (22.10.2018) =
* .po, .mo is updated for all the other languages.

Version 4.4.6

---

woocommerce-delivery-notes/includes/wcdn-welcome.php

Correct string #77

---

woocommerce-delivery-notes/readme.txt
woocommerce-delivery-notes/woocommerce-delivery-notes.php

Fix - When a noticed was dismissed from the plugin, then it will dismiss all other notices from other plugins also. This is fixed now.
Fix - Some errors in debug.log file are fixed.

Version 4.4.8

---

woocommerce-delivery-notes/includes/class-wcdn-print.php
woocommerce-delivery-notes/includes/class-wcdn-settings.php
woocommerce-delivery-notes/includes/class-wcdn-theme.php
woocommerce-delivery-notes/includes/class-wcdn-writepanel.php
woocommerce-delivery-notes/includes/class-woocommerce-delivery-notes.php
woocommerce-delivery-notes/includes/wcdn-template-functions.php
woocommerce-delivery-notes/includes/wcdn-template-hooks.php
woocommerce-delivery-notes/templates/print-order/print-content.php
woocommerce-delivery-notes/templates/print-order/print-footer.php
woocommerce-delivery-notes/templates/print-order/print-header.php
woocommerce-delivery-notes/templates/print-order/print-order.php
woocommerce-delivery-notes/uninstall.php
woocommerce-delivery-notes/woocommerce-delivery-notes.php

Making code changes as per WPCS coding standards. Also tested for compatibility with WooCommerce 3.7.

Making code changes as per WPCS coding standards

---

woocommerce-delivery-notes/includes/class-wcdn-print.php
woocommerce-delivery-notes/uninstall.php

Removed prepare() & query variable.
Fix #92
Removed all data when plugin is uninstalled.
Fix #95 Fix #96

Removed warnings & proper data cleanup upon uninstall

---

woocommerce-delivery-notes/includes/class-wcdn-writepanel.php

Fixing buttons not appearing on Order detail page.
Fix #100
Fix #101

Silly errors in code

---

woocommerce-delivery-notes/includes/class-woocommerce-delivery-notes.php
woocommerce-delivery-notes/readme.txt
woocommerce-delivery-notes/woocommerce-delivery-notes.php

= 4.5.0 (21.08.2019) =
* Added a missing file from v4.4.9.

Version 4.5.0

---

woocommerce-delivery-notes/includes/class-woocommerce-delivery-notes.php
woocommerce-delivery-notes/readme.txt
woocommerce-delivery-notes/woocommerce-delivery-notes.php

Changelog for v4.5.2: Fixed the issue of Print buttons not working on PHP versions below 7.0.

Version 4.5.2

---

woocommerce-delivery-notes/readme.txt
woocommerce-delivery-notes/woocommerce-delivery-notes.php

Changelog for v4.5.3 (26.09.2019)
* The plugin now allows 3rd party code to add order item data on the print-content.php template. Props to @doozy for the PR.

Version 4.5.3

---

woocommerce-delivery-notes/readme.txt

Updated readme file with links to 7 plugins & also updated the tags.

Updating readme file

---

woocommerce-delivery-notes/readme.txt
woocommerce-delivery-notes/woocommerce-delivery-notes.php

Compatibility with WooCommerce v4.0.0

Version 4.5.4

---

woocommerce-delivery-notes/readme.md
woocommerce-delivery-notes/readme.txt
woocommerce-delivery-notes/woocommerce-delivery-notes.php

Changed the name of the plugin to 'Print Invoice & Delivery Notes for WooCommerce"

Version 4.5.5

---

woocommerce-delivery-notes/readme.txt

5.4 Compatibility and Tags updation

5.4 Compatibility and Tags updation

---

woocommerce-delivery-notes/templates/print-order/print-content.php

Added the total quantity of the products in the row in the invoice notes.
Fixes #132

Added the total quantity of the products in the row in the invoice notes

---

woocommerce-delivery-notes/includes/class-wcdn-writepanel.php

Bulk printing was not working due to the old hooks & filters.Also, there was an issue of Print Dialog Box appears when we change the status in bulk. Both the issues are fixed in this commit.
Fixes #130
Fixes #131

Bulk printing was not working due to the old hooks & filters.

---

woocommerce-delivery-notes/readme.txt
woocommerce-delivery-notes/woocommerce-delivery-notes.php

Changed the version number and Upto Tag and have also updated readme.txt file for V4.6.0

Changed the version number and Upto Tag and have also updated readme.txt file for V4.6.0

---

woocommerce-delivery-notes/readme.txt

Updated compatibility with WP5.5

Updated compatibility with WP5.5

---

woocommerce-delivery-notes/includes/component/tracking-data/ts-tracking.php

Tracker Cron event was not running properly.This is fixed now
Fixes #122

Tracker Cron event was not running properly.

---

woocommerce-delivery-notes/includes/class-wcdn-writepanel.php

Added filters so that one can change the options name in the bulk action dropdown.
Fixes #147

Added filters so that one can change the options name in the bulk action dropdown

---

woocommerce-delivery-notes/readme.txt
woocommerce-delivery-notes/woocommerce-delivery-notes.php

Changed the version number to 4.6.1 & updated changelog for v4.6.1

Version 4.6.1

---

woocommerce-delivery-notes/includes/wcdn-template-functions.php
woocommerce-delivery-notes/templates/print-order/print-content.php

PIF fields were not coming in the invoice. This is fixed now.
Fixes #156

PIF fields were not coming in the invoice.

---

woocommerce-delivery-notes/includes/class-wcdn-settings.php
woocommerce-delivery-notes/includes/class-wcdn-theme.php

Added option to show print link in admin emails.
Fixes #134

Added option to show print link in admin emails

---

woocommerce-delivery-notes/includes/wcdn-all-component.php
woocommerce-delivery-notes/readme.txt

Updated FAQ with the new code for adding Product image
Fixes #154

Updated FAQ with the new code for adding Product image

---

woocommerce-delivery-notes/includes/class-wcdn-writepanel.php
woocommerce-delivery-notes/languages/woocommerce-delivery-notes.pot

Strings were not getting translated ,this is fixed now.
Also, have updated the .pot file.
Fixes #166

Strings were not getting translated

---

woocommerce-delivery-notes/includes/class-woocommerce-delivery-notes.php
woocommerce-delivery-notes/readme.txt
woocommerce-delivery-notes/woocommerce-delivery-notes.php

Changed changelog and version numbers for v4.6.2

Version 4.6.2

---

woocommerce-delivery-notes/readme.txt

Updated changelog

---

woocommerce-delivery-notes/readme.txt

Updated WP tested upto tag in readme file for WP5.7

WP tested upto 5.7

---

woocommerce-delivery-notes/woocommerce-delivery-notes.php

Changed the WC tested upto tag to 5.1

Wc upto tag 5.1

---

woocommerce-delivery-notes/includes/wcdn-template-functions.php
woocommerce-delivery-notes/templates/print-order/print-content.php
woocommerce-delivery-notes/templates/print-order/style.css

Shipping address was not coming in the invoice when the order was created manually.
Fixes #121
Fixes #155

issues-155-121

---

woocommerce-delivery-notes/includes/class-wcdn-print.php
woocommerce-delivery-notes/templates/new-template/print-content.php
woocommerce-delivery-notes/templates/new-template/print-footer.php
woocommerce-delivery-notes/templates/new-template/print-header.php
woocommerce-delivery-notes/templates/new-template/print-order.php
woocommerce-delivery-notes/templates/new-template/style.css

Custom development. Have added a new template as per the client's requirement.
Client's ticket: https://tychesoftwares.freshdesk.com/a/tickets/26739

Custom work

---

woocommerce-delivery-notes/includes/wcdn-all-component.php

After merging the PR for the milstone v4.6.5, the latest git copy was throwing the critical  error on installing.Hence fixed that in this commit.

Fatal error was coming on installing the latest git version.

---

woocommerce-delivery-notes/includes/wcdn-template-functions.php
woocommerce-delivery-notes/templates/print-order/print-content.php

Reverts TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#190

Revert "issue-150"

---

woocommerce-delivery-notes/includes/wcdn-template-functions.php

Fixed the issue of the logo visible on the Android phone.

---

woocommerce-delivery-notes/templates/print-order/print-content.php
woocommerce-delivery-notes/templates/print-order/style.css

Fixed the display of checkbox value selected on the product page(WooCommerce Product Add-ons plugin is active)

---

woocommerce-delivery-notes/includes/wcdn-template-functions.php

Fixed to remove redundant Refund line

---

woocommerce-delivery-notes/templates/print-order/print-content.php

Fixed the display labels for shipping and billing address

---

woocommerce-delivery-notes/includes/class-woocommerce-delivery-notes.php
woocommerce-delivery-notes/readme.txt
woocommerce-delivery-notes/woocommerce-delivery-notes.php

Changed the version number and added a changelog for version 4.7.0

Changed version number and added changelog for the version 4.7.0

---

includes/class-woocommerce-delivery-notes.php
woocommerce-delivery-notes.php

Updated the plugin version to 4.7.2

Version 4.7.2

---

readme.txt
woocommerce-delivery-notes.php

Added changelog, updated WP & WC tested up to values

Added changelog

---

templates/print-order/print-content.php

Fixed WooCommerce Product Add-ons Plugin Conflict

---

includes/class-wcdn-print.php
includes/class-wcdn-settings.php
includes/class-wcdn-writepanel.php
includes/wcdn-template-functions.php
readme.txt
woocommerce-delivery-notes.php

Added HPOS compatibility
Fix #259 
Fix #230

HPOS Compatibility

---

includes/wcdn-template-functions.php

Fixed Showing warning on the print invoices.

---

includes/admin/views/wcdn-comman-field.php

Fixed some warnings on template settings page.

---

includes/admin/views/wcdn-customization.php
includes/class-woocommerce-delivery-notes.php

Fixed Selected order status in attach email setting of the template is not set empty.

---

includes/admin/views/wcdn-customization.php

Fix #323. Added a check for when the hidden field is called.

 Fixed Showing warrnings on Invoice Settings page.

---

templates/print-order/simple/style.css

Fixed Payment Received stamp is not working in receipt templates settings

---

includes/admin/wcdn-admin-function.php

Removed template type field from template page. Added numbering option and email attach to option.

Removed template type field from template page.

---

assets/css/admin.css
assets/js/vue.js
assets/js/wdne-deliverynote-add-edit.js
assets/js/wdne-invoice-add-edit.js
assets/js/wdne-receipt-add-edit.js
includes/admin/views/Preview_template/deliverynote-preview-template.php
includes/admin/views/Preview_template/invoice-preview-template.php
includes/admin/views/Preview_template/receipt-preview-template.php
includes/admin/views/wcdn-document.php
includes/admin/wcdn-admin-function.php
includes/class-wcdn-settings.php
includes/wcdn-template-functions.php

live preview enhancement added on admin side

live preview enhancement

---

assets/css/admin.css

I removed some unnecessary code and adjusted the alignment of the fields to enhance their appearance.

Fixed Some css changes for new UI.

---

assets/js/admin.js
includes/class-wcdn-settings.php

Fix #332. The code will only work when the template is set to default. All fields will be disabled, except the first field.

Fixed Disable all the field when the default template is selected for new UI

---

includes/admin/wcdn-admin-function.php
includes/front/wcdn-front-function.php
includes/wcdn-template-functions.php

Fixed the code When the 'simple' template type is selected, all the print invoice display functions work properly and the invoice type 'creates invoice numbers' should work properly.

Fixed some of the functions to work properly after the UI changes.

---

includes/admin/wcdn-admin-function.php
includes/class-wcdn-settings.php

Fix changesui

---

assets/js/admin.js
includes/admin/views/Preview_template/deliverynote-preview-template.php
includes/admin/views/Preview_template/invoice-preview-template.php
includes/admin/views/Preview_template/receipt-preview-template.php
includes/admin/views/wcdn-document.php
includes/admin/views/wcdn-general.php
includes/admin/views/wcdn-header.php
includes/class-wcdn-settings.php
includes/wcdn-template-functions.php
woocommerce-delivery-notes.php

Fixed some issues which replicated during testing.
1. Logo size does not appear correct in Default template.
2. fixed need support Url.
3. Default billing title change.
4. Bulk action issue fix.
5. Added tooltip for Address, Complimentary Close, Policies,Footer.
6. Version number change.
7. Fix the fatal error on the template setting page. with a refunded order.
8. Added message on settings fields when default template is selected.

Fixed some issue

---

includes/admin/wcdn-admin-function.php
includes/class-wcdn-writepanel.php
includes/wcdn-template-functions.php

Fixed the numbering functionality to work properly. It will only work when the numbering option is enabled.

Removed checbox from the numbering option and added check for invoice number.

---

includes/admin/views/wcdn-document.php
includes/admin/views/wcdn-general.php
includes/class-wcdn-settings.php
includes/class-woocommerce-delivery-notes.php

Set default setting value to enable. Fix numbering checkbox value on the basis of the previous version. Change Setting Page name in woocomerece.

Set default setting value to enable

---

assets/css/adminstyle.css
includes/admin/views/Preview_template/deliverynote-preview-template.php
includes/admin/views/Preview_template/invoice-preview-template.php
includes/admin/views/Preview_template/receipt-preview-template.php
readme.txt

Added notice on live preview when there is no last order. [https://prnt.sc/jFIZ_YIxYWCN](https://prnt.sc/jFIZ_YIxYWCN)

Added notice on live preview when there is no last order

---

assets/js/admin.js
includes/admin/views/Preview_template/deliverynote-preview-template.php
includes/admin/views/Preview_template/invoice-preview-template.php
includes/admin/views/Preview_template/receipt-preview-template.php
includes/wcdn-template-functions.php
templates/print-order/simple/style.css
templates/print-order/style.css

fix payment method for default. and fetch invoice data  and payment date for live preview.

fix payment method for default

---

assets/css/adminstyle.css
assets/js/admin.js
readme.txt
templates/print-order/style.css

css changes and change hover message also added css for checkbox. also update changelog.

css change

---

assets/js/admin.js
readme.txt
templates/pdf/default/deliverynote/template.php
templates/pdf/default/invoice/template.php
templates/pdf/default/receipt/template.php
templates/pdf/default/style.css
woocommerce-delivery-notes.php

pdf order info css fixed for default template. [https://prnt.sc/RB0Vsz322Vaa](https://prnt.sc/RB0Vsz322Vaa)
WC version change, hover message spelling changes.

pdf css fixed

---

includes/admin/views/wcdn-document.php

tootltip message change

---

includes/wcdn-template-functions.php

added plugin version check to style.css [https://prnt.sc/a_iMvXPLWbUF](https://prnt.sc/a_iMvXPLWbUF)

added plugin version to style.css

---

assets/js/admin.js
includes/class-woocommerce-delivery-notes.php
includes/wcdn-template-functions.php
readme.txt
templates/print-order/simple/style.css
templates/print-order/style.css
woocommerce-delivery-notes.php

reverting the bulk action issue #298 . also, remove the mobile logo code

revert the bulk action fix

---

includes/class-woocommerce-delivery-notes.php
readme.txt
woocommerce-delivery-notes.php

version change pr

---

templates/print-order/simple/style.css

Fix #367 Added page-break for simple template.

Fix #367 added page-break

---

includes/class-wcdn-print.php
includes/wcdn-template-functions.php

Fix #371 pass array into $args for making compatible with woo donations plugin.

Fix #371 pass array in to $args

---

templates/print-order/print-header.php

Added Meta name and content in the head section of the template. [https://prnt.sc/wytg6RYOBRhm](url)
Ticket- [https://wordpress.org/support/topic/how-to-deindexed-invoice-page/](url)

Added Meta for robots noindex

---

includes/class-wcdn-writepanel.php
includes/wcdn-template-functions.php

Fix #366 Fixed Trying to access array offset on value of type null and Undefined array key "numbering".

Fix- #366 Fixed PHP Warnings

---

templates/pdf/default/deliverynote/template.php
templates/pdf/default/invoice/template.php
templates/pdf/default/receipt/template.php
templates/pdf/simple/deliverynote/template.php
templates/pdf/simple/invoice/template.php
templates/pdf/simple/receipt/template.php
templates/pdf/simple/style.css

Fix #370  Added wcdn_head_pdf hook in the PDF for changing css. also added font-size to simple pdf

Fix #370 Added this hook wcdn_head_pdf

---

includes/class-woocommerce-delivery-notes.php
readme.txt
woocommerce-delivery-notes.php

version change 5.1.0

---

includes/class-wcdn-theme.php

Fix #391 Added  '**wcdn_show_print_button_for_order_status**' filter for show print button on my account page on the basis of order status.

Fix #391 Added filter for show print button on my account page on the basis of order status

---

includes/admin/views/wcdn-general.php
includes/component/plugin-tracking/class-tyche-plugin-tracking.php
languages/woocommerce-delivery-notes.po
languages/woocommerce-delivery-notes.pot

Fix #384 Strings that have not been translation ready

Fix #384 Strings that have not been translation ready

---

includes/component/plugin-deactivation/class-tyche-plugin-deactivation.php
includes/wcdn-all-component.php

Fixed deactivation survey changes reported by woo.

Fixed deactivation survey changes

---

includes/class-woocommerce-delivery-notes.php
includes/wcdn-all-component.php
readme.txt
woocommerce-delivery-notes.php

version change and remove WCDN_TS_Faq_Support line.

version change

---

includes/admin/views/Preview_template/default-preview-template.php
includes/admin/views/Preview_template/deliverynote-preview-template.php
includes/admin/views/Preview_template/invoice-preview-template.php
includes/admin/views/Preview_template/receipt-preview-template.php
includes/wcdn-template-functions.php
templates/pdf/default/deliverynote/template.php
templates/pdf/default/invoice/template.php
templates/pdf/default/receipt/template.php
templates/pdf/simple/deliverynote/template.php
templates/pdf/simple/invoice/template.php
templates/pdf/simple/receipt/template.php
templates/print-order/print-content.php
templates/print-order/simple/deliverynote/print-content.php
templates/print-order/simple/invoice/print-content.php
templates/print-order/simple/receipt/print-content.php

Fix #381 refund issues

---

readme.txt
woocommerce-delivery-notes.php

changelog 5.2.0

---

includes/class-wcdn-print.php

Fix #403 Anyone can view customer invoices only by visiting the URL

Fix #403 Anyone can view customer invoices only by visiting the URL

---

includes/admin/views/wcdn-general.php

Fix #402 Added stripcslashes for address.

Fix #402 textarea value is not properly adding

---

includes/admin/views/wcdn-document.php
templates/print-order/simple/deliverynote/print-content.php

Fix #406 A PHP notice is appearing.

Fix #406 A PHP notice is appearing.

---

includes/class-woocommerce-delivery-notes.php
readme.txt
woocommerce-delivery-notes.php

version-change-5.3.0

---

readme.txt
woocommerce-delivery-notes.php

readme changes

---

includes/class-wcdn-print.php
includes/wcdn-template-functions.php
includes/wcdn-template-hooks.php

Fix #412 added 16 digit token for non login user, with that token now the token link is accessible for non login user. 
Also change the blank page link to redirect it to the login page and after login redirect it to that invoice link.

Fix #412 added token for non login users

---

includes/class-wcdn-print.php
includes/class-woocommerce-delivery-notes.php
readme.txt
woocommerce-delivery-notes.php

version change to 5.4.0

---

includes/class-wcdn-settings.php

Fix #417 fix security issue.

---

includes/class-woocommerce-delivery-notes.php
readme.txt
woocommerce-delivery-notes.php

version change and changelog-5.4.1

---

includes/class-wcdn-writepanel.php

Fix #426 Getting a fatal error.

Fix #426 Getting a fatal error.

---

includes/class-wcdn-theme.php
includes/front/wcdn-front-function.php

Fix #424 security issue

---

includes/wcdn-template-functions.php

Fix #425 logo is appearing as broken with the template.

Fix #425 logo is appearing as broken with the Simple template

---

includes/class-wcdn-print.php

Fix #418 Added 'allow_user_email_order_access' filter for non login user

Fix #418 Added a filter for non login user

---

includes/class-wcdn-writepanel.php

Fix #298 bulk action issue

---

includes/class-wcdn-writepanel.php

Fix #298 done some modificaion in css

Fix #298 done some modificaion in css

---

templates/print-order/simple/style.css

Blank page is adding at the end of the invoice

Blank page is adding at the end of the invoice

---

includes/class-wcdn-writepanel.php

Fix #434 Added pluralized Template type. [https://prnt.sc/ckT7yvgrFF-c](https://prnt.sc/ckT7yvgrFF-c)

Fix #434 Added pluralized Template type

---

includes/class-woocommerce-delivery-notes.php
readme.txt
woocommerce-delivery-notes.php

Changelog and version change added

Changelog and version change added

---

includes/class-wcdn-print.php

Fix #369 Invoice template now added in ascending order.

Fix #369 Invoice template now added ascending order.

---

includes/admin/views/Preview_template/default-preview-template.php
includes/admin/views/Preview_template/deliverynote-preview-template.php
includes/admin/views/Preview_template/invoice-preview-template.php
includes/admin/views/Preview_template/receipt-preview-template.php
includes/wcdn-template-functions.php
includes/wcdn-template-hooks.php
templates/pdf/default/deliverynote/template.php
templates/pdf/default/invoice/template.php
templates/pdf/default/receipt/template.php
templates/pdf/simple/deliverynote/template.php
templates/pdf/simple/invoice/template.php
templates/pdf/simple/receipt/template.php
templates/print-order/print-content.php
templates/print-order/simple/deliverynote/print-content.php
templates/print-order/simple/invoice/print-content.php
templates/print-order/simple/receipt/print-content.php

Fix #442 added prefix to our function.

Fix #442 added prefix to our function.

---

assets/js/admin.js
includes/admin/views/wcdn-general.php
includes/class-wcdn-settings.php

Fix #440 added nonce verfication for  vulnerability issue.

Fix #440 added nonce verfication for  vulnerability issue.

---

includes/class-wcdn-writepanel.php

Fix #437 Getting an error when printing the invoice.

Fix #437 Getting an error when printing the invoice.

---

includes/admin/views/Preview_template/default-preview-template.php
templates/pdf/default/deliverynote/template.php
templates/pdf/default/invoice/template.php
templates/pdf/default/receipt/template.php
templates/print-order/print-content.php

Fix #446 remove $key and $order.

Fix #446 remove $key and $order.

---

includes/class-woocommerce-delivery-notes.php
readme.txt
woocommerce-delivery-notes.php

version change pr - 5.6.0

---

includes/admin/views/Preview_template/default-preview-template.php
templates/print-order/print-content.php

Reverts TycheSoftwares/woocommerce-delivery-notes#452

Revert "Fix #451 variation item meta issue."
